# Pokemon Dataset

This project aims to analyze Pokémon attributes using statistical analysis and visualization to identify patterns across Pokémon types and to compare the overall strength of Legendary and non-Legendary Pokémon.

In [1]:
import pandas as pd

In [16]:
data=pd.read_csv('Pokemon.csv')
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [18]:
data.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [20]:
data.drop(columns=['#'],inplace=True)

In [21]:
data

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Dataset Overview
This dataset contains information about Pokémon including their types, base stats, generation, and legendary status.

In [22]:
data.shape

(800, 12)

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        800 non-null    object
 1   Type 1      800 non-null    object
 2   Type 2      414 non-null    object
 3   Total       800 non-null    int64
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [25]:
data.isnull().sum()

Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [28]:
data['Type 2']=data['Type 2'].replace(pd.NA,'None')
data

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,None,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [29]:
data.isna().sum()

Name          0
Type 1        0
Type 2        0
Total         0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

How many Pokémon are there in the dataset?

In [36]:
data.shape[0]

800

What are the average values of each base stat?

In [38]:
data.columns

Index(['Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [41]:
data[['HP', 'Attack', 'Defense','Sp. Atk', 'Sp. Def', 'Speed']].mean()

HP         69.25875
Attack     79.00125
Defense    73.84250
Sp. Atk    72.82000
Sp. Def    71.90250
Speed      68.27750
dtype: float64

Which Pokémon has the highest Total Stats?

In [44]:
# Creating the total_stats column
data['total_stats']=data['HP']+data['Attack']+data['Defense']+data['Sp. Atk']+data['Sp. Def']+data['Speed']
data

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total_stats
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
4,Charmander,Fire,None,309,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,600
796,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,700
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,600
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,680
799,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,600

In [51]:
data.loc[data['total_stats'].idxmax()]

Name           MewtwoMega Mewtwo X
Type 1                     Psychic
Type 2                    Fighting
Total                          780
HP                             106
Attack                         190
Defense                        100
Sp. Atk                        154
Sp. Def                        100
Speed                          130
Generation                       1
Legendary                     True
total_stats                    780
Name: 163, dtype: object

How many Legendary and Non-Legendary Pokémon are there?

In [52]:
data['Legendary'].value_counts()

Legendary
False    735
True      65
Name: count, dtype: int64

Do Legendary Pokémon have higher average Total Stats?

In [53]:
data.groupby('Legendary')['total_stats'].mean()

Legendary
False    417.213605
True     637.384615
Name: total_stats, dtype: float64

Which Pokémon Type (Type 1) has the highest average Total Stats?

In [55]:
data.groupby('Type 1')['total_stats'].mean().sort_values(ascending=False)

Type 1
Dragon      550.531250
Steel       487.703704
Flying      485.000000
Psychic     475.947368
Fire        458.076923
Rock        453.750000
Dark        445.741935
Electric    443.409091
Ghost       439.562500
Ground      437.500000
Ice         433.458333
Water       430.455357
Grass       421.142857
Fighting    416.444444
Fairy       413.176471
Normal      401.683673
Poison      399.142857
Bug         378.927536
Name: total_stats, dtype: float64

What is the distribution of Pokémon generations?

In [56]:
data['Generation'].value_counts().sort_index()

Generation
1    166
2    106
3    160
4    121
5    165
6     82
Name: count, dtype: int64

Which stat has the highest variability?

In [57]:
data[['HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']].std()

HP         25.534669
Attack     32.457366
Defense    31.183501
Sp. Atk    32.722294
Sp. Def    27.828916
Speed      29.060474
dtype: float64

Is Attack correlated with Speed?

In [58]:
data[['Attack','Speed']].corr()

         Attack    Speed
Attack  1.00000  0.38124
Speed   0.38124  1.00000

Are single-type Pokémon more common than dual-type Pokémon?

In [59]:
data['Type 2'].isnull().value_counts()

Type 2
False    800
Name: count, dtype: int64